apiVersion: v1
kind: Service
metadata:
  name: mcmp-demo-uigitlab-1-3-gitlab
  namespace: ocp-on-aws-b9eb-ns
spec:
  ports:
  - name: mcmp-demo-uigitlab-1-3-gitlab-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitlab-1-3-gitlab
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
